#!/usr/bin/env bash

mapfile -t items
shopt -s checkwinsize
exec 6>&1 < /dev/tty > /dev/tty

trap 'printf "\e[H%*s\e8\e[?7h" "$COLUMNS" ""' EXIT
trap 'REPLY=redraw; break' WINCH

printf '\e7\e[?7l'
while true; do
	(:)
	[[ ${text_cache-${text}x} != "$text" ]] && {
		unset sel max_items matches

		for item in "${items[@]}"; do
			case $item in
				$text)		: 0 ;;
				$text*)		: 1 ;;
				*$text*)	: 2 ;;
				*)		continue ;;
			esac

			matches[_]+=$'\n'$item
			(( ${#item} > longest )) && longest=${#item}
		done

		mapfile -s 1 -t matches <<< "${matches[@]}"
		index=(0 0)
	}

	printf '\e[?25l\e[H\e[30;41m %s%*s\e[m' \
		"$text" \
		$(( longest - ${#text} + 4 )) "${index[2]:+<} "

	(( index == max_items )) && {
		unset length max_items
		(( length += longest + 5 ))
		(( max_items += index ))

		for (( i = index; i < ${#matches[@]}; i++ )); do
			if (( length < COLUMNS - ${#matches[i]} - 7 )); then
				(( length += ${#matches[i]} + 2 ))
				(( max_items++ ))
			else
				printf '\e[30;41m\e[;%sH%*s\e[;%sH%s\n\e[m' \
					$(( COLUMNS - (COLUMNS - length) )) \
					$(( COLUMNS - length )) "" \
					$(( COLUMNS - 1 )) "> "
				(( length = COLUMNS ))
				break
			fi
		done

		(( sel && sel >= max_items )) && {
			(( index = max_items ))
			continue
		}
	}

	[[ -n ${matches[*]} ]] && {
		printf '\e[;%sH' $(( longest - ${#text} + 6 ))
		matches[sel]=$'\e[m\e[D\e[1;37;7m '${matches[sel]}
		printf '\e[30;41m %s \e[m' \
			"${matches[@]:index:max_items-index}"
		matches[sel]=${matches[sel]#$'\e[m\e[D\e[1;37;7m '}
	}

	printf '\e[30;41m%*s\e[m\e[?25h\e[;%sH' \
		$(( COLUMNS - length )) "" \
		$(( ${#text} + 2 ))

	until read -t 0.05 -rsn 1; do :; done

	if [[ $REPLY == $'\e' ]]; then
		read -t 0.01 -rsn 2 key
		key=${REPLY}${key}
	elif [[ $REPLY == redraw ]]; then
		(( max_items = index ))
		continue
	else
		key=$REPLY
	fi

	text_cache=$text

	case $key in
		"" | $'\r')
			printf '\e8'
			if (( ${#matches[@]} )); then
				printf '%s\n' "${matches[sel]}"
			else
				printf '%s\n' "$text"
			fi >&6
			printf '\e7'
			break
			;;
		$'\e')
			exit
			;;
		$'\e[D' | $'\e[A')
			(( sel > 0 && sel-- && sel == index - 1 )) && {
				index[0]=${index[${#index[@]}-2]}
				unset index[${#index[@]}-1]
				(( max_items = index ))
			}
			;;
		$'\e[C' | $'\e[B')
			((
				sel < ${#matches[@]} - 1 &&
				++sel &&
				sel == max_items &&
				max_items < ${#items[@]}
			)) && {
				index[${#index[@]}]=$max_items
				index[0]=$max_items
			}
			;;
		$'\177' | $'\b')
			text=${text%?}
			;;
		$'\t')
			text=${matches[sel]}
			;;
		*)
			text+=$key
			;;
	esac
done
