#!/usr/bin/env bash

mapfile -t items
shopt -s checkwinsize
exec 6>&1 </dev/tty >/dev/tty

trap 'printf "\e[H%*s\e8\e[?7h" "$COLUMNS" ""' EXIT
trap '[[ -z $REPLY ]] && {
	REPLY=redraw
	break
}' WINCH

printf '\e7\e[?7l'
while true; do
	(:)
	[[ ${text_cache-${text}x} != "$text" ]] && {
		unset sel max_items matches

		for item in "${items[@]}"; do
			case $item in
				$text)		: 0 ;;
				$text*)		: 1 ;;
				*$text*)	: 2 ;;
				*)		continue ;;
			esac

			matches[_]+=$'\n'$item
			(( ${#item} > longest )) && longest=${#item}
		done

		mapfile -s 1 -t matches \
			<<< "${matches[0]}${matches[1]}${matches[2]}"
		index=(0 0)
	}

	printf '\e[?25l\e[H\e[30;41m %s%*s\e[m' \
		"$text" \
		$(( longest - ${#text} + 4 )) "${index[2]:+<} "

	(( index == max_items )) && {
		unset length max_items
		(( length += longest + 5 ))
		(( max_items += index ))

		for (( i = index; i < ${#matches[@]}; i++ )); do
			if (( length < COLUMNS - ${#matches[i]} - 7 )); then
				(( length += ${#matches[i]} + 2 ))
				(( max_items++ ))
			else
				printf '\e[30;41m\e[;%sH%*s\e[;%sH%s\n\e[m' \
					$(( COLUMNS - (COLUMNS - length) )) \
					$(( COLUMNS - length )) "" \
					$(( COLUMNS - 1 )) "> "
				(( length = COLUMNS ))
				break
			fi
		done

		(( sel && sel >= max_items )) && {
			(( index = max_items ))
			continue
		}
	}

	[[ -n ${matches[*]} ]] && {
		matches[sel]=$'\e[m\e[D\e[7m '${matches[sel]}
		printf '\e[;%sH' $(( longest + 6 ))
		printf '\e[30;41m %s \e[m' \
			"${matches[@]:index:max_items-index}"
		matches[sel]=${matches[sel]#$'\e[m\e[D\e[7m '}
	}

	printf '\e[30;41m%*s\e[m\e[?25h\e[;%sH' \
		$(( COLUMNS - length )) "" \
		$(( ${#text} + 2 ))

	until read -t 0.05 -rsn 1; do :; done

	if [[ $REPLY == $'\e' ]]; then
		read -t 0.01 -rsn 2 key
		key=${REPLY}${key}
	else
		key=$REPLY
	fi

	text_cache=$text

	case $key in
		"" | $'\r')
			printf '\e8'
			if (( ${#matches[@]} )); then
				printf '%s\n' "${matches[sel]}"
			else
				printf '%s\n' "$text"
			fi >&6
			printf '\e7'
			break
			;;
		$'\e')
			exit
			;;
		$'\e'[\[O][DA])
			(( sel > 0 && sel-- && sel == index - 1 )) && {
				index[0]=${index[-2]}
				unset index[-1]
				(( max_items = index ))
			}
			;;
		$'\e'[\[O][CB])
			((
				sel < ${#matches[@]} - 1 &&
				++sel &&
				sel == max_items &&
				max_items < ${#items[@]}
			)) && {
				index+=("$max_items")
				index[0]=$max_items
			}
			;;
		$'\177' | $'\b')
			text=${text%?}
			;;
		$'\t')
			text=${matches[sel]}
			;;
		redraw)
			(( max_items = index ))
			continue
			;;
		*)
			text+=$key
			;;
	esac
done
