#!/usr/bin/env bash

shopt -s checkwinsize
IFS=$'\n' read -t 0.01 -d "" -ra items

trap '{
	printf "\e8\e[?7h" > /dev/tty
	[[ -n $output ]] && printf "%s\n" "$output"
}' EXIT

printf '\e7\e[?7l' > /dev/tty
while true; do
	[[ -z ${starting[@]} ]] && starting=(0 0)
	unset matches length max_items
	for i in "${!items[@]}"; do
		[[ ${items[i]} == *"$text"* ]] && {
			matches+=("${items[i]}")
			(( ${#items[i]} > longest )) && longest=${#items[i]}
		}
	done

	(( length += longest + 5 ))
	(( max_items += starting ))

	(:)
	printf '\e[?25l\e[H\e[30;41m %s%*s\e[m' \
		"$text" \
		$(( longest - ${#text} + 4 )) "${starting[2]:+<} "

	for (( i = starting; i < ${#matches[@]}; i++ )); do
		if (( length < COLUMNS - ${#matches[i]} - 7 )); then
			(( length += ${#matches[i]} + 2 ))
			(( max_items++ ))
		else
			printf '\e[30;41m%*s\e[;%sH%s\n\e[m' \
				$(( COLUMNS - length )) "" \
				$(( COLUMNS - 1 )) ">"
			(( length = COLUMNS ))
			break
		fi

		if (( i == sel )); then
			printf '\e[1;37;7m %s \e[m' "${matches[i]}"
		else
			printf '\e[30;41m %s \e[m' "${matches[i]}"
		fi
	done

	printf '\e[30;41m%*s\e[m\e[?25h\e[;%sH' \
		$(( COLUMNS - length )) "" \
		$(( ${#text} + 2 ))

	read -srn 1
	if [[ $REPLY == $'\e' ]]; then
		read -rsn 2 key
		key=${REPLY}${key}
	else
		key=$REPLY
	fi
	read -t 0.01 -d "" -rs _

	case $key in
		"" | $'\r')
			printf '\e8'
			if (( ${#matches[@]} )); then
				output=${matches[sel]}
			else
				output=$text
			fi
			printf '\e7'
			break
			;;
		$'\e[D' | $'\e[A')
			#echo "${#starting[@]}" :"${starting[@]}"; read -t 0.05
			#echo "${starting[@]}"; sleep 1
			#(( ${#starting[@]} > 2 )) && echo "${starting[@]}" && sleep 9999
			#(:;:); (:;:); (:;:)
			(( sel > 0 && sel-- && sel == starting - 1 )) && {
				#sleep 1
				#set -x
				starting[0]=${starting[${#starting[@]}-2]}
				unset starting[${#starting[@]}-1]
				#sleep 1
				#set +x
			}
				#starting[0]=${starting[${#starting[@]}-1]}
			;;
		$'\e[C' | $'\e[B')
			#sel < max_items &&
			#(:;:); (:;:); (:;:)
			((
				sel < ${#matches[@]} - 1 &&
				sel++ &&
				sel == max_items &&
				max_items < ${#items[@]}
			)) && {
				starting[${#starting[@]}]=$max_items
				starting[0]=$max_items
			}
			;;
		$'\177' | $'\b')
			(( ${#text} > 0 )) && {
				text=${text:: -1}
				unset sel starting
			}
			;;
		*)
			text+=$key
			unset sel starting
			;;
	esac
done < /dev/tty > /dev/tty
